- hosts: app
  user: root
  tasks:
    - name: check centos version
      shell: cat /etc/redhat-release | awk '{print $(NF-1)}' | cut -c1

    - name: get current time
      command: /bin/date +%s
      register: before_reboot
      sudo: false

    - name: Restart server
      shell: sleep 2 && shutdown -r now "Ansible package updates triggered"
      async: 1
      poll: 0
      ignore_errors: true
      become: true

    - name: waiting 60 secs for server to come back
      local_action: wait_for host={{ ansible_default_ipv4.address }} port=22 state=started delay=60 timeout=120
      become: false

    - name: verify a reboot was actually initiated
      # machine should have started after it has been rebooted
      shell: (( `date +%s` - `awk -F . '{print $1}' /proc/uptime` > {{ before_reboot.stdout }} ))
      sudo: false

