- hosts: all
  become: yes
  tasks:
    - name: install apache2
      yum: name={{ item }} state=present
      with_items:
       - httpd
       - php
       - php-mysql

    - name: install apache on redhat or centos instances
      yum: name=httpd state=present
      when: ansible_os_family == "RedHat"
    - name: enable apache on startup and start service for redhat or centos
      service: name=httpd enabled=yes state=started
      when: ansible_os_family == "RedHat"
